language: c

services:
    - docker

before_install:
    - docker pull ezechiel/eternity:latest
    - docker run -itd --name eternity ezechiel/eternity

script:
    - docker exec eternity cmake -DBUILD_TESTING=ON -H/eternity -B/build
    - docker exec eternity cmake --build /build
    - docker exec eternity cmake --build /build --target test
